type EmojiRule = {
  emoji: string;
  keywords: string[];
};

const EMOJI_RULES: EmojiRule[] = [
  {
    emoji: "🛒",
    keywords: [
      "shopping",
      "shop",
      "buy",
      "buying",
      "buyer",
      "purchase",
      "purchases",
      "purchasing",
      "grocery",
      "groceries",
      "supermarket",
      "market",
      "compras",
      "compra",
      "comprar",
      "comprando",
      "mercado",
      "supermercado",
      "liste de courses",
      "courses",
      "acheter",
      "achat",
      "einkauf",
      "einkaufen",
      "einkaufsliste",
      "kaufen",
      "kauf",
      "spesa",
      "spese",
      "comprare",
      "acquistare",
      "compras supermercado",
      "zakupy",
      "kupic",
      "kupowac",
      "покупки",
      "магазин",
      "购物",
      "買い物",
      "쇼핑",
      "장보기",
      "تسوق",
      "مشتريات",
      "खरीदारी",
      "खरीददारी",
      "खरीद",
    ],
  },
  {
    emoji: "🍔",
    keywords: [
      "food",
      "meal",
      "meals",
      "menu",
      "restaurant",
      "restaurante",
      "comida",
      "cena",
      "almuerzo",
      "desayuno",
      "recetas",
      "receta",
      "kitchen",
      "cocina",
      "essen",
      "rezepte",
      "rezepte",
      "ristorante",
      "cibo",
      "еда",
      "питание",
      "음식",
      "식사",
      "料理",
      "食事",
      "美食",
      "餐",
      "مطعم",
      "طبخ",
      "وجبات",
      "भोजन",
      "खाना",
    ],
  },
  {
    emoji: "💼",
    keywords: [
      "work",
      "office",
      "job",
      "business",
      "meeting",
      "meetings",
      "trabajo",
      "oficina",
      "empresa",
      "reunion",
      "reuniones",
      "agenda laboral",
      "arbeit",
      "buero",
      "beruf",
      "firma",
      "lavoro",
      "ufficio",
      "travail",
      "bureau",
      "работа",
      "офис",
      "会议",
      "工作",
      "仕事",
      "업무",
      "회사",
      "عمل",
      "وظيفة",
      "कार्यालय",
      "काम",
    ],
  },
  {
    emoji: "📚",
    keywords: [
      "study",
      "studies",
      "school",
      "college",
      "university",
      "homework",
      "exam",
      "exams",
      "class",
      "classes",
      "estudio",
      "estudiar",
      "escuela",
      "universidad",
      "tarea",
      "tareas",
      "examen",
      "estudi",
      "schule",
      "lernen",
      "studium",
      "hausaufgaben",
      "prüfung",
      "pruefung",
      "cours",
      "etudes",
      "scuola",
      "studio",
      "учеба",
      "учёба",
      "школа",
      "экзамен",
      "学习",
      "学校",
      "勉強",
      "試験",
      "공부",
      "시험",
      "دراسة",
      "مدرسة",
      "امتحان",
      "पढ़ाई",
      "पढाई",
      "स्कूल",
      "परीक्षा",
    ],
  },
  {
    emoji: "✈️",
    keywords: [
      "travel",
      "travelling",
      "traveling",
      "trip",
      "trips",
      "vacation",
      "holiday",
      "flights",
      "flight",
      "hotel",
      "viaje",
      "viajes",
      "viajar",
      "vacaciones",
      "vuelo",
      "vuelos",
      "hoteles",
      "reisen",
      "reise",
      "reisen planen",
      "reisenplan",
      "urlaub",
      "flug",
      "fluege",
      "fluge",
      "hotel",
      "viaggio",
      "viaggi",
      "viaggiare",
      "voyage",
      "voyager",
      "путешествие",
      "поездка",
      "旅行",
      "航班",
      "ホテル",
      "여행",
      "비행기",
      "호텔",
      "سفر",
      "رحلة",
      "فندق",
      "यात्रा",
      "सफर",
      "होटल",
    ],
  },
  {
    emoji: "🏠",
    keywords: [
      "home",
      "house",
      "hogar",
      "casa",
      "casa tareas",
      "home chores",
      "cocina casa",
      "heim",
      "zuhause",
      "haus",
      "maison",
      "casa hogar",
      "дом",
      "домашние",
      "家",
      "家庭",
      "집",
      "가정",
      "منزل",
      "بيت",
      "घर",
      "गृह",
    ],
  },
  {
    emoji: "💰",
    keywords: [
      "finance",
      "finances",
      "money",
      "budget",
      "bills",
      "bill",
      "expenses",
      "expense",
      "tax",
      "bank",
      "banking",
      "wallet",
      "finanzas",
      "dinero",
      "presupuesto",
      "gastos",
      "facturas",
      "impuestos",
      "banco",
      "finanzen",
      "geld",
      "budget",
      "rechnung",
      "rechnungen",
      "steuern",
      "banque",
      "soldi",
      "finanza",
      "финансы",
      "деньги",
      "бюджет",
      "счета",
      "налоги",
      "银行",
      "预算",
      "账单",
      "お金",
      "家計",
      "예산",
      "지출",
      "은행",
      "مال",
      "ميزانية",
      "فواتير",
      "بنك",
      "पैसे",
      "बजट",
      "बिल",
      "कर",
      "बैंक",
    ],
  },
  {
    emoji: "💊",
    keywords: [
      "health",
      "medical",
      "doctor",
      "medicine",
      "medication",
      "pharmacy",
      "hospital",
      "salud",
      "medico",
      "doctor",
      "medicina",
      "farmacia",
      "hospital",
      "arzt",
      "gesundheit",
      "medizin",
      "apotheke",
      "krankenhaus",
      "sante",
      "medecin",
      "farmacia",
      "ospedale",
      "здоровье",
      "врач",
      "лекарство",
      "аптека",
      "больница",
      "健康",
      "医生",
      "药",
      "医院",
      "病院",
      "薬",
      "건강",
      "병원",
      "약",
      "صحة",
      "طبيب",
      "دواء",
      "صيدلية",
      "مستشفى",
      "स्वास्थ्य",
      "डॉक्टर",
      "दवा",
      "अस्पताल",
    ],
  },
  {
    emoji: "🏋️",
    keywords: [
      "gym",
      "workout",
      "fitness",
      "training",
      "exercise",
      "running",
      "run",
      "sport",
      "sports",
      "entrenar",
      "entreno",
      "ejercicio",
      "gimnasio",
      "deporte",
      "correr",
      "carrera",
      "fit",
      "training",
      "sport",
      "laufen",
      "gym",
      "allenamento",
      "correre",
      "спорт",
      "тренировка",
      "бег",
      "健身",
      "锻炼",
      "跑步",
      "運動",
      "筋トレ",
      "ランニング",
      "운동",
      "헬스",
      "러닝",
      "رياضة",
      "تمرين",
      "جري",
      "व्यायाम",
      "कसरत",
      "दौड़",
      "दौड",
    ],
  },
  {
    emoji: "🚗",
    keywords: [
      "car",
      "auto",
      "vehicle",
      "garage",
      "mechanic",
      "mecanic",
      "itv",
      "coche",
      "carro",
      "vehiculo",
      "taller",
      "gasolina",
      "gas",
      "fuel",
      "auto",
      "wagen",
      "fahrzeug",
      "werkstatt",
      "benzin",
      "voiture",
      "mecanicien",
      "машина",
      "авто",
      "гараж",
      "бензин",
      "汽车",
      "车",
      "駐車",
      "車",
      "자동차",
      "차",
      "سيارة",
      "وقود",
      "carro oficina",
      "गाड़ी",
      "गाडी",
      "कार",
      "ईंधन",
      "ईधन",
    ],
  },
  {
    emoji: "🐾",
    keywords: [
      "pet",
      "pets",
      "dog",
      "cat",
      "mascota",
      "mascotas",
      "perro",
      "gato",
      "veterinario",
      "veterinary",
      "haustier",
      "haustiere",
      "hund",
      "katze",
      "tierarzt",
      "animale",
      "chien",
      "chat",
      "животное",
      "питомец",
      "собака",
      "кошка",
      "兽医",
      "宠物",
      "狗",
      "猫",
      "ペット",
      "犬",
      "猫",
      "반려동물",
      "강아지",
      "고양이",
      "حيوان",
      "حيوانات",
      "قط",
      "كلب",
      "पालतू",
      "कुत्ता",
      "बिल्ली",
    ],
  },
  {
    emoji: "🎁",
    keywords: [
      "gift",
      "gifts",
      "birthday",
      "cumple",
      "cumpleanos",
      "cumpleaños",
      "regalo",
      "regalos",
      "fiesta",
      "party",
      "evento",
      "anniversaire",
      "cadeau",
      "geschenk",
      "geburtstag",
      "geburtstags",
      "fete",
      "compleanno",
      "подарок",
      "день рождения",
      "生日",
      "礼物",
      "誕生日",
      "プレゼント",
      "생일",
      "선물",
      "هدية",
      "عيد ميلاد",
      "उपहार",
      "जन्मदिन",
    ],
  },
  {
    emoji: "🧹",
    keywords: [
      "clean",
      "cleaning",
      "chores",
      "tidy",
      "limpieza",
      "limpiar",
      "ordenar",
      "tareas casa",
      "aseo",
      "putzen",
      "haushalt",
      "aufräumen",
      "aufräumen",
      "menage",
      "nettoyage",
      "pulizia",
      "уборка",
      "чистка",
      "清洁",
      "打扫",
      "掃除",
      "청소",
      "تنظيف",
      "सफाई",
      "साफ",
    ],
  },
  {
    emoji: "🌱",
    keywords: [
      "garden",
      "plant",
      "plants",
      "jardin",
      "jardineria",
      "plantas",
      "huerto",
      "jardim",
      "garten",
      "pflanze",
      "pflanzen",
      "orto",
      "giardino",
      "сад",
      "растения",
      "садоводство",
      "园艺",
      "植物",
      "庭",
      "ガーデン",
      "정원",
      "식물",
      "حديقة",
      "نبات",
      "बगीचा",
      "पौधा",
    ],
  },
  {
    emoji: "💡",
    keywords: [
      "idea",
      "ideas",
      "brainstorm",
      "notes",
      "note",
      "inspiration",
      "idea list",
      "idea banco",
      "ideas",
      "notas",
      "apuntes",
      "inspiracion",
      "ideen",
      "notizen",
      "inspiration",
      "idee",
      "memo",
      "идеи",
      "заметки",
      "想法",
      "笔记",
      "アイデア",
      "メモ",
      "아이디어",
      "메모",
      "افكار",
      "فكرة",
      "ملاحظات",
      "आइडिया",
      "विचार",
      "नोट्स",
    ],
  },
];

function normalizeText(raw: string): string {
  return raw
    .toLocaleLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\p{L}\p{N}\s]/gu, " ")
    .replace(/\s+/g, " ")
    .trim();
}

const NON_SEGMENTED_SCRIPT_RE = /[\u4E00-\u9FFF\u3040-\u30FF\uAC00-\uD7AF]/u;
const LATIN_WORD_RE = /^[a-z0-9]+$/u;
const STEM_SUFFIXES = [
  "amientos",
  "imientos",
  "amiento",
  "imiento",
  "aciones",
  "adores",
  "adoras",
  "acion",
  "adora",
  "ador",
  "mente",
  "idades",
  "idad",
  "ismos",
  "ismo",
  "istas",
  "ista",
  "ancias",
  "ancia",
  "encias",
  "encia",
  "yendo",
  "iendo",
  "ando",
  "ings",
  "ing",
  "ados",
  "adas",
  "idos",
  "idas",
  "es",
  "ed",
  "ar",
  "er",
  "ir",
  "s",
];

function stemLatinWord(word: string): string {
  let value = word;
  for (const suffix of STEM_SUFFIXES) {
    if (value.length <= suffix.length + 2) continue;
    if (!value.endsWith(suffix)) continue;
    value = value.slice(0, -suffix.length);
    break;
  }
  if (value.length > 4 && /[aeiou]$/u.test(value)) {
    value = value.slice(0, -1);
  }
  return value;
}

function tokenMatchesKeyword(token: string, keyword: string): boolean {
  if (!token || !keyword) return false;
  if (token === keyword) return true;

  const tokenIsLatin = LATIN_WORD_RE.test(token);
  const keywordIsLatin = LATIN_WORD_RE.test(keyword);

  if (tokenIsLatin && keywordIsLatin) {
    const tokenStem = stemLatinWord(token);
    const keywordStem = stemLatinWord(keyword);
    const minStemLen = Math.min(tokenStem.length, keywordStem.length);
    if (
      minStemLen >= 3 &&
      (tokenStem === keywordStem ||
        tokenStem.startsWith(keywordStem) ||
        keywordStem.startsWith(tokenStem))
    ) {
      return true;
    }

    const minRawLen = Math.min(token.length, keyword.length);
    if (
      minRawLen >= 3 &&
      (token.startsWith(keyword) || keyword.startsWith(token))
    ) {
      return true;
    }
  }

  return false;
}

function findKeywordPosition(
  normalizedText: string,
  keyword: string,
  tokens: string[],
  tokenStarts: number[],
): number {
  if (!keyword) return -1;

  if (keyword.includes(" ") || NON_SEGMENTED_SCRIPT_RE.test(keyword)) {
    return normalizedText.indexOf(keyword);
  }

  for (let i = 0; i < tokens.length; i += 1) {
    if (tokenMatchesKeyword(tokens[i], keyword)) {
      return tokenStarts[i] ?? -1;
    }
  }

  return -1;
}

export function suggestSharedListEmoji(title: string): string | null {
  const normalized = normalizeText(title);
  if (!normalized) return null;

  const tokens = normalized.split(" ");
  const tokenStarts: number[] = [];
  let cursor = 0;
  for (const token of tokens) {
    tokenStarts.push(cursor);
    cursor += token.length + 1;
  }

  let winner: { emoji: string; position: number; ruleIndex: number } | null = null;

  for (let ruleIndex = 0; ruleIndex < EMOJI_RULES.length; ruleIndex += 1) {
    const rule = EMOJI_RULES[ruleIndex];
    for (const rawKeyword of rule.keywords) {
      const keyword = normalizeText(rawKeyword);
      if (!keyword) continue;
      const position = findKeywordPosition(normalized, keyword, tokens, tokenStarts);
      if (position < 0) continue;

      if (
        !winner ||
        position < winner.position ||
        (position === winner.position && ruleIndex < winner.ruleIndex)
      ) {
        winner = { emoji: rule.emoji, position, ruleIndex };
      }
    }
  }

  return winner ? winner.emoji : null;
}
